# Generated by Django 5.1.6 on 2025-02-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('any', 'Anyone'), ('email', 'Email required')], default='email', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('publish', 'Published'), ('soon', 'coming soon'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
