# Generated by Django 5.1.6 on 2025-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
